package br.ufscar.dc.compiladores.planner;

public class GeradorHTMLUtils {
    public static final String ANUAL_STYLES = "        <style>"
    + "        .container {"
    + "    padding: 0 5%;"
    + "}"
    + "    .calendar {"
    + "    justify-content: space-between;"
    + "    display: flex;"
    + "    flex-wrap: wrap;"
    + "}"
    + "    .container-tarefa {"
    + "    justify-content: space-between;"
    + "    display: flex;"
    + "    flex-wrap: wrap;"
    + "}"
    + "    .tarefa {"
    + "    width: 45%;"
    + "}"
    + "    .mes {"
    + "    /*display: flex;*/"
    + "    /*flex-direction: row;*/"
    + "    margin: 5px;"
    + "    width: 45%;"
    + "    min-height: 300px;"
    + "    border: 2px solid black;"
    + "    border-radius: 3%;"
    + "}"
    + "h1 {"
    + "    text-align: center;"
    + "}"
    + "h3 {"
    + "    margin: 0;"
    + "    padding: 15px;"
    + "    text-align: center;"
    + "    /*writing-mode: vertical-rl;*/"
    + "    /*text-orientation: upright;*/"
    + "}"
    + "ul {"
    + "    list-style-type: none;"
    + "    margin: 0 20px;"
    + "    padding: 0;"
    + "}"
    + "li {"
    + "    margin-bottom: 5px;"
    + "}"
    + "    .bold {"
    + "    font-weight: bold;"
    + "}"
    + "</style>";
}
